GET http://localhost:8081/using-api-publicauthorities/api/my
Accept: */*
Content-Type: application/json
Cache-Control: no-cache
Authorization: Basic YXBwX3VzZXI6dGVzdDEyMw==

{
  "id": "100",
  "comment": "хаха"
}

###